name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "**/*.js"
      - "package.json"
      - "app.json"
      - "eas.json"
      - ".github/workflows/build.yml"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Auth to Expo
        run: eas whoami || eas login --token $EXPO_TOKEN
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android (APK)
        run: eas build --platform android --profile preview --non-interactive --wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
